### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by chowooseoung** [chowooseoung/domino#1]
- [ ] mGear 의 spine_ik_02 를 구현할 방법을 찾아야함. legnth to param 노드가 없으므로 바이프로스트를 조사.
- [ ] keyframe 저장 구현하기.
- [ ] spine_01 component 의 volume, orient lock 구현하기.

**Comment by chowooseoung** [comment]
이슈 세분화.
